name: CI

on:
  - pull_request
  - push

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends clang git make pkg-config libgnutls28-dev libgcrypt20-dev libglib2.0-dev prosody gcovr
        sudo prosodyctl stop

    - name: build bitlbee
      run: |
        ./configure --asan=1
        cat ./.tests/gcovflags >> Makefile.settings
        make
        sudo make install
        touch ./debuglog
    
    - name: talk to bitlbee
      run: |
        ./.tests/setup_bitlbee.sh

        python3 ./.tests/talk_to_bitlbee.py

        ./.tests/cleanup_bitlbee.sh

    - name: jabber: connect
        ./.tests/setup_prosody.sh
        ./.tests/setup_bitlbee.sh

        python3 ./.tests/test1.py

        ./.tests/cleanup_bitlbee.sh
        ./.tests/cleanup_prosody.sh

    - name: code coverage
      if: ${{ always() }}
      run: |
        gcovr -r .
